# Generated by Django 6.0.6 on 2026-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'New York Stock Exchange')], default='NSE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='stocks_symbol_7bc68d_idx'), models.Index(fields=['sector'], name='stocks_sector_88fdef_idx')],
            },
        ),
    ]
